# Generated by Django 5.0.6 on 2026-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('no_of_colors', models.PositiveIntegerField(default=1)),
                ('ratio', models.JSONField(blank=True, help_text='e.g. {"S": 1, "M": 2, "L": 2}', null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Total qty, required for FIXED_QUANTITY', null=True)),
                ('order_type', models.CharField(choices=[('FIXED_QUANTITY', 'Fixed Quantity'), ('RATIO_BASED', 'Ratio Based')], max_length=20)),
                ('resting_needed', models.BooleanField(default=False)),
                ('approved_average', models.DecimalField(decimal_places=3, help_text='Approved fabric consumption per piece', max_digits=8)),
                ('inner_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fusing_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_repeat', models.BooleanField(default=False, verbose_name='New Repeat')),
                ('remarks', models.TextField(blank=True)),
                ('total_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_CUTTING', 'In Cutting'), ('IN_PRODUCTION', 'In Production'), ('IN_FINISHING', 'In Finishing'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('colors', models.ManyToManyField(related_name='orders', to='master_data.color')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
    ]
