# Generated by Django 5.0.6 on 2026-07-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('orders', '0002_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_average',
        ),
        migrations.RemoveField(
            model_name='order',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fusing_required',
        ),
        migrations.RemoveField(
            model_name='order',
            name='inner_required',
        ),
        migrations.RemoveField(
            model_name='order',
            name='no_of_colors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='order',
            name='resting_needed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rolls_to_be_used',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_average', models.DecimalField(decimal_places=3, help_text='Approved fabric consumption per piece', max_digits=8)),
                ('inner_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fusing_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('resting_needed', models.BooleanField(default=False)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='master_data.fabrictype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='master_data.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_colors', to='master_data.color')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='orders.orderitem')),
                ('rolls', models.ManyToManyField(blank=True, related_name='order_item_colors', to='store.fabricstock')),
            ],
            options={
                'unique_together': {('order_item', 'color')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Set when order_type = FIXED_QUANTITY', null=True)),
                ('ratio_part', models.PositiveIntegerField(blank=True, help_text='Set when order_type = RATIO_BASED', null=True)),
                ('order_item_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_lines', to='orders.orderitemcolor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_size_lines', to='master_data.size')),
            ],
            options={
                'ordering': ['size__display_order'],
                'unique_together': {('order_item_color', 'size')},
            },
        ),
    ]
