# Generated by Django 5.0.6 on 2026-07-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_approved_average_remove_order_colors_and_more'),
    ]

    operations = [
        # AlterField would try to cast the existing numeric column straight
        # to boolean, which Postgres refuses. There are no Order rows yet,
        # so drop and recreate instead of migrating data.
        migrations.RemoveField(model_name='orderitem', name='fusing_required'),
        migrations.RemoveField(model_name='orderitem', name='inner_required'),
        migrations.AddField(
            model_name='orderitem',
            name='fusing_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inner_required',
            field=models.BooleanField(default=False),
        ),
    ]
