# Generated by Django 5.0.6 on 2026-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_fusing_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Operator stitching payment per finished piece, set by Merchandising when the order is created. Every operator who completes a piece of this order line is paid this rate x pieces returned.', max_digits=10),
        ),
    ]
