# Generated by Django 5.0.6 on 2026-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_price_per_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cutting_instruction',
            field=models.TextField(blank=True, help_text="Instruction for the Cutting floor, e.g. 'Use only half of each roll for every colour, return the rest'. Store issues the full rolls; Cutting follows this note and returns the leftover."),
        ),
    ]
