# Generated by Django 5.0.6 on 2026-07-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cutting_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcolor',
            name='half_roll',
            field=models.BooleanField(default=False, help_text="Merchandising's 'use only half of each roll for this colour' flag. Cutting sees it per colour and cuts ~half the issued fabric, returning the rest."),
        ),
    ]
