# Generated by Django 5.0.6 on 2026-07-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitemcolor_half_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_piece',
        ),
    ]
