# Generated by Django 5.0.6 on 2026-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_price_per_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_CUTTING', 'In Cutting'), ('IN_PRODUCTION', 'In Production'), ('IN_FINISHING', 'In Finishing'), ('DISPATCHED', 'Dispatched'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
