# Generated by Django 5.0.6 on 2026-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_category',
            field=models.CharField(choices=[('BULK', 'Bulk Production'), ('SAMPLE', 'Sample')], default='BULK', help_text='Sample = a small pre-production run for client approval; Bulk = the full production order.', max_length=20),
        ),
    ]
