# Generated by Django 5.0.6 on 2026-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sample_decided_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sample_feedback',
            field=models.TextField(blank=True, help_text='Client feedback captured with the approve/reject decision.'),
        ),
        migrations.AddField(
            model_name='order',
            name='sample_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text="Client's decision on a sample, recorded once it is dispatched/completed.", max_length=20),
        ),
    ]
