# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField(default=True)),
                ('defects_found', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('checked_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('bundle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='cutting.bundle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
