# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutting', '0003_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlereceipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionqualitycheck',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_qc_checks', to='cutting.bundle'),
        ),
        migrations.AddField(
            model_name='productionqualitycheck',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_checks', to=settings.AUTH_USER_MODEL),
        ),
    ]
