# Generated by Django 5.0.6 on 2026-07-13 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_fusing_required_and_more'),
        ('production', '0002_initial'),
        ('store', '0004_fabricstock_supplied_by_party'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('accessory_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='store.accessorystock')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_issues_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_issues', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
