# Generated by Django 5.0.6 on 2026-07-14 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0006_bundle_sent_by_bundle_sent_to_production_at'),
        ('operators', '0004_bundleassignment_defect_reason_and_more'),
        ('production', '0003_accessoryissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleAccessoryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('accessory_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_allocations', to='production.accessoryissue')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_issues', to='cutting.bundle')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_accessory_issues_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_issues', to='operators.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
