# Generated by Django 5.0.6 on 2026-07-18 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_bundleassignment_defect_reason_and_more'),
        ('orders', '0006_order_cutting_instruction'),
        ('production', '0004_bundleaccessoryissue'),
        ('store', '0005_accessorystock_supplied_by_party'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAccessoryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pieces_covered', models.PositiveIntegerField(default=0, help_text='Garment pieces the used accessories went into.')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('accessory_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_direct_issues', to='store.accessorystock')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_accessory_issues_made', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_accessory_issues', to='operators.operator')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_accessory_issues', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
