# Generated by Django 5.0.6 on 2026-07-18 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_productcomponent'),
        ('orders', '0006_order_cutting_instruction'),
        ('production', '0005_operatoraccessoryissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('department', models.CharField(choices=[('WASHING', 'Washing'), ('PRINTING', 'Printing'), ('EMBROIDERY', 'Embroidery'), ('DYEING', 'Dyeing'), ('FINISHING', 'Finishing'), ('OTHER', 'Other')], max_length=20)),
                ('quantity_sent', models.PositiveIntegerField()),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.PositiveIntegerField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('is_outsourced', models.BooleanField(default=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent — Awaiting Return'), ('RECEIVED', 'Received Back')], default='SENT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_dispatches', to='orders.order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_dispatches_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_dispatches_sent', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_dispatches', to='master_data.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
