# Generated by Django 5.0.6 on 2026-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_processdispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdispatch',
            name='department',
            field=models.CharField(choices=[('WASHING', 'Washing'), ('PRINTING', 'Printing'), ('EMBROIDERY', 'Embroidery'), ('FINISHING', 'Finishing')], max_length=20),
        ),
    ]
