# Generated by Django 5.0.6 on 2026-07-19 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_processdispatch_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processdispatch',
            name='loss_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processdispatch',
            name='loss_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processdispatch',
            name='loss_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processdispatch',
            name='loss_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_loss_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processdispatch',
            name='loss_status',
            field=models.CharField(choices=[('NONE', 'No Shortage'), ('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='processdispatch',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent — Awaiting Return'), ('PENDING_APPROVAL', 'Shortage — Awaiting Admin Approval'), ('RECEIVED', 'Received Back')], default='SENT', max_length=20),
        ),
    ]
