# Generated by Django 5.0.6 on 2026-07-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_processdispatch_loss_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdispatch',
            name='cost_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Outsourced processing rate per piece; total cost = rate x quantity_sent.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processdispatch',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total processing cost (auto-computed = cost_per_piece x quantity_sent when a per-piece rate is given).', max_digits=12, null=True),
        ),
    ]
