# Generated by Django 5.0.6 on 2026-07-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_processdispatch_cost_per_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdispatch',
            name='department',
            field=models.CharField(choices=[('WASHING', 'Washing'), ('PRINTING', 'Printing'), ('EMBROIDERY', 'Embroidery'), ('BUTTON', 'Button'), ('FINISHING', 'Finishing')], max_length=20),
        ),
    ]
