# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt (from Merchandise/Purchase)'), ('ISSUE', 'Issue (to Cutting)'), ('WASTAGE', 'Wastage'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, help_text='PO number, cutting order number, etc.', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FabricStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Fabric width (inches)', max_digits=6, null=True)),
                ('unit', models.CharField(choices=[('METERS', 'Meters'), ('YARDS', 'Yards'), ('KILOGRAMS', 'Kilograms'), ('GRAMS', 'Grams'), ('ROLLS', 'Rolls')], default='METERS', max_length=20)),
                ('roll_number', models.CharField(blank=True, max_length=100)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='master_data.color')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='master_data.fabrictype')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_stocks', to='master_data.vendor')),
            ],
        ),
    ]
