# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='fabric_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.fabricstock'),
        ),
        migrations.AddIndex(
            model_name='fabricstock',
            index=models.Index(fields=['fabric_type', 'color'], name='store_fabri_fabric__e32d0d_idx'),
        ),
    ]
