# Generated by Django 5.0.6 on 2026-07-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_alter_accessory_color'),
        ('store', '0003_accessorystock_accessorystocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricstock',
            name='supplied_by_party',
            field=models.ForeignKey(blank=True, help_text='Set when this stock originated from a customer-supplied purchase, so it can be traced back to that customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_fabric_stocks', to='master_data.party'),
        ),
    ]
