# Generated by Django 5.0.6 on 2026-07-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_productcomponent'),
        ('store', '0004_fabricstock_supplied_by_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorystock',
            name='supplied_by_party',
            field=models.ForeignKey(blank=True, help_text='Set when this stock originated from a customer-supplied purchase, so it can be traced back to that customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_accessory_stocks', to='master_data.party'),
        ),
    ]
