# Generated by Django 5.0.6 on 2026-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_finishedgoodsreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricstock',
            name='unit',
            field=models.CharField(choices=[('METERS', 'Meters'), ('YARDS', 'Yards'), ('KILOGRAMS', 'Kilograms'), ('GRAMS', 'Grams')], default='METERS', max_length=20),
        ),
    ]
