# Generated by Django 5.0.6 on 2026-07-22 14:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitemcolor_half_roll'),
        ('store', '0007_alter_fabricstock_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('CUSTOMS', 'Customs'), ('LABOUR', 'Labour'), ('STORAGE', 'Storage'), ('WASHING', 'Washing'), ('PRINTING', 'Printing'), ('EMBROIDERY', 'Embroidery'), ('FINISHING', 'Finishing'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_additional_charges', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
