# Generated by Django 5.0.6 on 2026-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderadditionalcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadditionalcharge',
            name='charge_type',
            field=models.CharField(choices=[('TRANSPORT', 'Transport / Freight'), ('COURIER', 'Courier'), ('CUSTOMS', 'Customs Clearance'), ('STORAGE', 'Storage / Warehousing'), ('SAMPLE', 'Sample Development'), ('TESTING', 'Testing / Inspection'), ('PENALTY', 'Late Delivery Penalty'), ('LABOUR', 'Labour / Handling'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
