# Generated by Django 5.0.6 on 2026-07-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('master_data', '0004_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_supplied', to='master_data.party'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='master_data.accessory'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='master_data.color'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='master_data.fabrictype'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_type',
            field=models.CharField(choices=[('FABRIC', 'Fabric'), ('ACCESSORY', 'Accessory')], default='FABRIC', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master_data.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
