# Generated by Django 5.0.6 on 2026-07-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_purchaseorder_party_purchaseorderitem_accessory_and_more'),
        ('orders', '0004_alter_orderitem_fusing_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Optional -- attribute this expense to one order (e.g. a one-off courier cost) when relevant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='orders.order'),
        ),
    ]
