# Generated by Django 5.0.6 on 2026-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expenserecord_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='no_of_rolls',
            field=models.PositiveIntegerField(default=1, help_text='For fabric: how many physical rolls this quantity arrives in. A customer supplying 5 rolls of White 110 m each is quantity=550, no_of_rolls=5 -> 5 separate stock rolls.'),
        ),
    ]
