# Generated by Django 5.0.6 on 2026-07-19 11:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchaseorderitem_no_of_rolls'),
        ('master_data', '0009_alter_accessory_unit'),
        ('orders', '0007_orderitemcolor_half_roll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_per_piece', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_till', models.DateField()),
                ('terms', models.TextField(blank=True, help_text='Payment and delivery terms.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Order'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='orders.order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='master_data.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='master_data.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
