# Generated by Django 5.0.6 on 2026-07-23 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_customerinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='customer_invoice',
            field=models.ForeignKey(blank=True, help_text='The sales invoice this payment was recorded against (audit link).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='finance.customerinvoice'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online')], max_length=20),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='reference',
            field=models.CharField(blank=True, help_text='Cheque/transaction/UTR number for the audit trail.', max_length=100),
        ),
    ]
