# Generated by Django 5.0.6 on 2026-07-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_incomerecord_customer_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='additional_costs',
            field=models.JSONField(blank=True, default=dict, help_text='Post-invoice extra charges billed to the customer, {label: amount}. Folded into `amount`.'),
        ),
    ]
