# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finishing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dispatched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='orders.order'),
        ),
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_qc_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_qc_checks', to='orders.order'),
        ),
        migrations.AddField(
            model_name='packing',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='orders.order'),
        ),
        migrations.AddField(
            model_name='packing',
            name='packed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packings', to=settings.AUTH_USER_MODEL),
        ),
    ]
