# Generated by Django 5.0.6 on 2026-07-14 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0002_initial'),
        ('master_data', '0007_productcomponent'),
        ('orders', '0004_alter_orderitem_fusing_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='delivery_acknowledged_by',
            field=models.CharField(blank=True, help_text='Customer-side name acknowledging receipt.', max_length=150),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road'), ('AIR', 'Air'), ('COURIER', 'Courier'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='quantity_dispatched',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FinishingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('WASHING', 'Washing'), ('PRINTING', 'Printing'), ('IRONING', 'Ironing'), ('EMBROIDERY', 'Embroidery'), ('PACKAGING', 'Packaging'), ('LABELING', 'Labeling'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_outsourced', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('performed_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_operations', to='orders.order')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_operations_recorded', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_operations', to='master_data.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinishingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_sent', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_receipts', to='orders.order')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_receipts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
