# Generated by Django 5.0.6 on 2026-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0003_dispatch_delivery_acknowledged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingoperation',
            name='quantity_rejected',
            field=models.PositiveIntegerField(default=0, help_text='Pieces damaged/rejected during this specific finishing operation (washing, printing, etc).'),
        ),
    ]
