# Generated by Django 5.0.6 on 2026-07-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0004_finishingoperation_quantity_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='quantity_altered',
            field=models.PositiveIntegerField(default=0, help_text='Pieces sent for alteration/rework.'),
        ),
    ]
