# Generated by Django 5.0.6 on 2026-07-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0005_finishingqualitycheck_quantity_altered'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='quantity_reworked_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='quantity_reworked_passed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
