# Generated by Django 5.0.6 on 2026-07-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0006_finishingqualitycheck_quantity_reworked_failed_and_more'),
        ('master_data', '0009_alter_accessory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='challan_number',
            field=models.CharField(blank=True, help_text='Delivery challan number.', max_length=100),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='color_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Pieces dispatched per colour, e.g. {"White": 40, "Black": 30}.'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='size_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Pieces dispatched per size, e.g. {"S": 30, "M": 40}.'),
        ),
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_qc_checks', to='master_data.color'),
        ),
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_qc_checks', to='master_data.size'),
        ),
    ]
