# Generated by Django 5.0.6 on 2026-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0007_dispatch_challan_number_dispatch_color_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='alter_reason',
            field=models.TextField(blank=True, help_text='Why the altered pieces need alteration.'),
        ),
        migrations.AddField(
            model_name='finishingqualitycheck',
            name='fail_reason',
            field=models.TextField(blank=True, help_text='Why the failed pieces failed (per colour+size row).'),
        ),
    ]
