# Generated by Django 5.0.6 on 2026-07-27 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0008_finishingqualitycheck_alter_reason_and_more'),
        ('operators', '0008_bundleassignment_paid_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Altered pieces handed to this operator to rework.')),
                ('rate_per_piece', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('returned_quantity', models.PositiveIntegerField(blank=True, help_text='Pieces the operator reworked and handed back.', null=True)),
                ('paid_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated — Operator Reworking'), ('COMPLETED', 'Reworked — Returned to Finishing')], default='ALLOCATED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_allocations', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_assignments', to='operators.operator')),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_assignments', to='finishing.finishingqualitycheck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
