# Generated by Django 5.0.6 on 2026-08-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing', '0009_reworkassignment'),
        ('orders', '0011_order_sample_decided_date_order_sample_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='orders.order'),
        ),
    ]
