# Generated by Django 5.0.6 on 2026-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, default='', help_text='e.g. #1E3A8A', max_length=7),
        ),
    ]
