# Generated by Django 5.0.6 on 2026-07-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_color_hex_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_type', models.CharField(choices=[('ZIPPER', 'Zipper'), ('BUTTON', 'Button'), ('THREAD', 'Thread'), ('ELASTIC', 'Elastic'), ('LABEL', 'Label'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('size_spec', models.CharField(blank=True, default='', help_text='e.g. 20mm, 18L, 40/2', max_length=100)),
                ('unit', models.CharField(choices=[('PIECES', 'Pieces'), ('METERS', 'Meters'), ('YARDS', 'Yards'), ('ROLLS', 'Rolls'), ('CONES', 'Cones'), ('DOZEN', 'Dozen')], default='PIECES', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='master_data.color')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'unique_together': {('accessory_type', 'name', 'size_spec', 'color')},
            },
        ),
    ]
