# Generated by Django 5.0.6 on 2026-07-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='master_data.color'),
        ),
    ]
