# Generated by Django 5.0.6 on 2026-07-13 11:20

import re
from django.db import migrations, models


def backfill_code_prefix(apps, schema_editor):
    Party = apps.get_model("master_data", "Party")
    for party in Party.objects.filter(code_prefix=""):
        party.code_prefix = (re.sub(r"[^A-Za-z]", "", party.name or "")[:2] or "XX").upper()
        party.save(update_fields=["code_prefix"])


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_alter_accessory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='code_prefix',
            field=models.CharField(blank=True, help_text="Short prefix used in generated order codes, e.g. 'HU' for Huba. Auto-derived from name if left blank.", max_length=10),
        ),
        migrations.RunPython(backfill_code_prefix, migrations.RunPython.noop),
    ]
