# Generated by Django 5.0.6 on 2026-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_productcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text="Link to the style's reference image (front photo / tech-pack shot). Shown in the admin Product Gallery.", max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_chart',
            field=models.JSONField(blank=True, default=list, help_text="Size-wise measurement spec: a list of rows like [{'param': 'Chest (in)', 'sizes': {'S': '38', 'M': '40', 'L': '42'}}]."),
        ),
    ]
