# Generated by Django 5.0.6 on 2026-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_product_image_url_product_measurement_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='unit',
            field=models.CharField(choices=[('PIECES', 'Pieces'), ('METERS', 'Meters'), ('YARDS', 'Yards'), ('KILOGRAMS', 'Kilograms'), ('CONES', 'Cones'), ('DOZEN', 'Dozen')], default='PIECES', max_length=20),
        ),
    ]
