# Generated by Django 5.0.6 on 2026-07-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_accessory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Style category, e.g. T-Shirts, Hoodies, Cargos, Leggings.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_types',
            field=models.ManyToManyField(blank=True, help_text='Fabric options this style can be made in (e.g. Pique, Single Jersey).', related_name='products', to='master_data.fabrictype'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_chart_url',
            field=models.URLField(blank=True, help_text='Link to the measurement-chart document (e.g. a PDF tech pack).', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Apparel', 'Apparel'), ('Knitwear', 'Knitwear'), ('Bottomwear', 'Bottomwear'), ('Outerwear', 'Outerwear'), ('Accessory', 'Accessory'), ('Other', 'Other')], default='Apparel', help_text='Broad classification of the style, e.g. Apparel.', max_length=50),
        ),
    ]
