# Generated by Django 5.0.6 on 2026-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_product_category_product_fabric_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded reference image of the style (optional).', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_chart_file',
            field=models.FileField(blank=True, help_text='Uploaded measurement-chart document, e.g. a PDF (optional).', null=True, upload_to='products/charts/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Legacy image link — kept for older styles; new styles upload an image instead.', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_chart_url',
            field=models.URLField(blank=True, help_text='Legacy measurement-chart link — kept for older styles; new styles upload a file instead.', max_length=500),
        ),
    ]
