# Generated by Django 5.0.6 on 2026-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_product_image_product_measurement_chart_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum outstanding receivable allowed for this buyer.', max_digits=14),
        ),
        migrations.AddField(
            model_name='party',
            name='credit_terms',
            field=models.CharField(blank=True, help_text='e.g. NET 30, NET 15, Advance, COD.', max_length=30),
        ),
        migrations.AddField(
            model_name='party',
            name='pan_vat',
            field=models.CharField(blank=True, max_length=30, verbose_name='PAN / VAT No.'),
        ),
    ]
