# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutting_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('fabric_issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wastage_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FABRIC_ISSUED', 'Fabric Issued'), ('CUTTING', 'Cutting In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('cutting_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuttingPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('QUALITY_CHECKED', 'Quality Checked')], default='CREATED', max_length=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='master_data.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='master_data.size')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
