# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutting', '0001_initial'),
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingorder',
            name='fabric_issued',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_orders', to='store.fabricstock'),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_orders', to='orders.order'),
        ),
    ]
