# Generated by Django 5.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutting', '0002_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingorder',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundle',
            name='cutting_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='cutting.cuttingorder'),
        ),
        migrations.AddField(
            model_name='cuttingpiece',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_pieces', to='master_data.color'),
        ),
        migrations.AddField(
            model_name='cuttingpiece',
            name='cutting_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='cutting.cuttingorder'),
        ),
        migrations.AddField(
            model_name='cuttingpiece',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_pieces', to='master_data.size'),
        ),
        migrations.AlterUniqueTogether(
            name='cuttingpiece',
            unique_together={('cutting_order', 'color', 'size')},
        ),
    ]
