# Generated by Django 5.0.6 on 2026-07-13 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0003_initial'),
        ('orders', '0004_alter_orderitem_fusing_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingorder',
            name='actual_average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='average_override_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='average_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='average_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='average_override_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='average_status',
            field=models.CharField(choices=[('PENDING', 'Not Cut Yet'), ('CUT', 'Cut'), ('DONT_CUT', "Don't Cut — Over Consumption"), ('NOT_APPLICABLE', 'No Approved Average To Check')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='fabric_used_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text="Auto-derived from the fabric roll's OrderItemColor link when possible.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_orders', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_orders_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_fabric_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='total_pieces_cut',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RECEIVED', 'Received by Production'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('QUALITY_CHECKED', 'Quality Checked')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuttingorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_orders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='cuttingorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FABRIC_ISSUED', 'Fabric Issued'), ('RECEIVED', 'Received'), ('CUTTING', 'Cutting In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
