# Generated by Django 5.0.6 on 2026-07-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0004_cuttingorder_actual_average_and_more'),
        ('master_data', '0007_productcomponent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuttingpiece',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='ratio_sets_cut',
            field=models.PositiveIntegerField(blank=True, help_text='Set only for Ratio-order cuts.', null=True),
        ),
        migrations.AddField(
            model_name='cuttingpiece',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_pieces', to='master_data.productcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='cuttingpiece',
            unique_together={('cutting_order', 'color', 'size', 'component')},
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marker_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('avg_consumption_per_set', models.DecimalField(decimal_places=3, help_text='Meters of fabric per one complete ratio set', max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fabric_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markers', to='master_data.fabrictype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_orders', to='cutting.marker'),
        ),
    ]
