# Generated by Django 5.0.6 on 2026-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0006_bundle_sent_by_bundle_sent_to_production_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingorder',
            name='layer_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length of one fabric layer in the lay (m).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='no_of_layers',
            field=models.PositiveIntegerField(blank=True, help_text='Total fabric layers spread & cut across all lays recorded.', null=True),
        ),
    ]
