# Generated by Django 5.0.6 on 2026-07-13 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleassignment',
            name='issued_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Pieces handed to the operator; defaults to the bundle's full quantity.", null=True),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='returned_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the operator actually returned.', null=True),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='shortage_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='shortage_reason_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'No Shortage'), ('PENDING_REVIEW', 'Pending Admin Review'), ('APPROVED', 'Reason Approved'), ('REJECTED', 'Reason Rejected')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='shortage_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='shortage_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='shortage_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortage_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bundleassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RETURNED', 'Returned — Pending Review'), ('COMPLETED', 'Completed'), ('QUALITY_CHECKED', 'Quality Checked')], default='ASSIGNED', max_length=20),
        ),
    ]
