# Generated by Django 5.0.6 on 2026-07-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_bundleassignment_issued_quantity_and_more'),
        ('orders', '0004_alter_orderitem_fusing_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleassignment',
            name='defect_reason',
            field=models.TextField(blank=True, help_text='Required when defects > 0.'),
        ),
        migrations.AddField(
            model_name='operatorincome',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='operatorrate',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order-specific rate override -- leave Product blank when this is set; it applies to all work on this order regardless of product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_rates', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='operatorincome',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
