# Generated by Django 5.0.6 on 2026-07-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_bundleassignment_defect_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatorRate',
        ),
    ]
