# Generated by Django 5.0.6 on 2026-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_delete_operatorrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleassignment',
            name='rate_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-piece pay rate agreed with the operator, set by Production at allocation; total pay = rate x pieces returned.', max_digits=10, null=True),
        ),
    ]
