# Generated by Django 5.0.6 on 2026-07-24 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_bundleassignment_rate_per_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='operator',
            name='group',
            field=models.ForeignKey(blank=True, help_text='If this operator is part of a group, select the group here.', limit_choices_to={'operator_type': 'GROUP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='operators.operator'),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_group_leader',
            field=models.BooleanField(default=False),
        ),
    ]
