# Generated by Django 5.0.6 on 2026-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_remove_operator_skill_level_operator_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleassignment',
            name='paid_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Of the returned pieces, how many have already been paid to the operator.'),
        ),
    ]
